### ISSUE TITLE
Rails instrumentation with meta programming is not happening

### ISSUE THREAD

**Issue by bhaskar-introhive** [Shopify/statsd-instrument#150]
When I try instrumenting a class in rails app with meta programming.
I have tried testing the instrumentation in 2 ways.

> 1. Calling directly Object method from rails console
> 2. Calling via Rails request

The first one have passed with successful result where as the 2nd one did not pass at all.
I am posting this after research. 

Can anyone tell me why the 2nd way is failing... ??

**Comment by wvanbergen** [comment]
I will need a bit more information to be of help here. Can you provide sample code and exactly what you did to test?
