### ISSUE TITLE
Add option to intercept tags

### ISSUE THREAD

**Issue by fabiormoura** [Shopify/statsd-instrument#155]
It would be nice to be able to attach or modify tags via an interceptor. The most common use case this is useful is when common tags(s) are used everywhere in code.

For instance, recently our platform team introduced the concept of `runtime` and they provided an interface to identify which `runtime` our service is currently running onto as in `Runtime.current`. 

We decided to add the runtime tag to all our metrics but we did that by monkey-patching [`StatsD::Metric#initialize`](https://github.com/Shopify/statsd-instrument/blob/808f62362c5acaf2caaa99d88ae4b8f39569e8aa/lib/statsd/instrument/metric.rb#L49) to insert the `runtime` tag into `@tags` as the snippet below shows:

```ruby

    RUNTIME_ID_PREFIX = "runtime_id:"

    def initialize(*)
      super
            @tags ||= []

      unless @tags.any? { |tag| tag.start_with?(RUNTIME_ID_PREFIX) }
        @tags << "#{RUNTIME_ID_PREFIX}#{Runtime.current}"
      end
    end

```

What are your thoughts to allow passing a new proc to StatsD and then use it for intercepting `tags` before `metric` is instantiated at https://github.com/Shopify/statsd-instrument/blob/808f62362c5acaf2caaa99d88ae4b8f39569e8aa/lib/statsd/instrument.rb#L462

```ruby
StatsD.tags_appender = proc do |tags|
  tags[:runtime_id] = Runtime.current
end
```

**Comment by wvanbergen** [comment]
The main hesitations I have that this would be a massive slowdown. StatsD calls are part of some extremely hot code paths, and introducing a `proc` for every call sounds very expensive
