### ISSUE TITLE
Memory leak when using BatchedUDPSink

### ISSUE THREAD

**Issue by vahe** [Shopify/statsd-instrument#297]
We noticed a memory leak on one of our Sidekiq deployments. With `rbtrace` and diffing heap dumps the indication was it was from `statsd-instrument` gem.

```
Retained STRING 755984 objects of size 221275072/228127604 (in bytes) at: /artifacts/bundle/ruby/2.7.0/gems/statsd-instrument-3.1.2/lib/statsd/instrument/datagram_builder.rb:86
```

After setting `STATSD_FLUSH_INTERVAL` to 0, the memory leak disappeared ([to use the UDPSink instead of BatchedUDPSink](https://github.com/Shopify/statsd-instrument/blob/61440b52456bd4b181f62113f25957aa7c20ce4e/lib/statsd/instrument/environment.rb#L92-L95))

Memory graphs before:
<img width=200 src="https://user-images.githubusercontent.com/1486701/136235821-d511df7a-837c-4bd0-962e-6910bb01e57c.png"/>

After:
<img width=400 src="https://user-images.githubusercontent.com/1486701/136235736-a9b7ce6f-95f7-47a7-be64-576dcf4fe1f9.png"/>

**Comment by casperisfine** [comment]
Sorry, somehow I wasn't watching the repo and didn't notice this.

A couple thoughts:

  - The default 1 second interval is likely too much. We should probably reduce it to 0.1 or something.
  - We need to handle and upper size to that array. A sleep loop isn't good enough, we need to wake up the background thread if the buffer is past a certain size. I think we could do this with a `Monitor`, I need to explore that.
