### ISSUE TITLE
Datadog Origin Detection support?

### ISSUE THREAD

**Issue by cwoodcox** [Shopify/statsd-instrument#321]
Datadog Origin Detection allows stats emitted by Workloads in Kubernetes clusters to be identified by the Datadog Agent running in the cluster. That way, the tags from that Workload specified by Datadog Autodiscovery can be added before shipping them to Datadog.

This is usually accomplished by adding a tag (`dd.internal.entity_id`) to all datagrams emitted, and the value of that tag is the Pod UID (usually provided via `DD_ENTITY_ID` ENV var).

The other option is support for Unix Domain Sockets, where Origin Detection happens automatically.

Any chance this library supports that in the future?

**Comment by casperisfine** [comment]
I suppose you can already do this since there is already a "default tags" support.

Automatically adding `DD_ENTITY_ID` in the default tags would be easy, feel free to submit a PR. But would be nice to link to some documentation.

**Comment by kleinkk76** [comment]
> Datadog Origin Detection allows stats emitted by Workloads in Kubernetes clusters to be identified by the Datadog Agent running in the cluster. That way, the tags from that Workload specified by Datadog Autodiscovery can be added before shipping them to Datadog.
> 
> This is usually accomplished by adding a tag (`dd.internal.entity_id`) to all datagrams emitted, and the value of that tag is the Pod UID (usually provided via `DD_ENTITY_ID` ENV var).
> 
> The other option is support for Unix Domain Sockets, where Origin Detection happens automatically.
> 
> Any chance this library supports that in the future?

https://github.com/Shopify/statsd-instrument/issues/321#issue-1422952645

**Comment by kleinkk76** [comment]
> Datadog Origin Detection allows stats emitted by Workloads in Kubernetes clusters to be identified by the Datadog Agent running in the cluster. That way, the tags from that Workload specified by Datadog Autodiscovery can be added before shipping them to Datadog.
> 
> This is usually accomplished by adding a tag (`dd.internal.entity_id`) to all datagrams emitted, and the value of that tag is the Pod UID (usually provided via `DD_ENTITY_ID` ENV var).
> 
> The other option is support for Unix Domain Sockets, where Origin Detection happens automatically.
> 
> Any chance this library supports that in the future?

https://github.com/Shopify/statsd-instrument/issues/321#issue-1422952645

> > Datadog Origin Detection allows stats emitted by Workloads in Kubernetes clusters to be identified by the Datadog Agent running in the cluster. That way, the tags from that Workload specified by Datadog Autodiscovery can be added before shipping them to Datadog.
> > This is usually accomplished by adding a tag (`dd.internal.entity_id`) to all datagrams emitted, and the value of that tag is the Pod UID (usually provided via `DD_ENTITY_ID` ENV var).
> > The other option is support for Unix Domain Sockets, where Origin Detection happens automatically.
> > Any chance this library supports that in the future?
> 
> [#321 (comment)](https://github.com/Shopify/statsd-instrument/issues/321#issue-1422952645)

https://github.com/Shopify/statsd-instrument/issues/321#issuecomment-1872996514

**Comment by casperisfine** [comment]
Closing this as we're not likely to implement it ourselves, but PR welcome.

**Comment by kleinkk76** [comment]
> I suppose you can already do this since there is already a "default tags" support.
> 
> Automatically adding `DD_ENTITY_ID` in the default tags would be easy, feel free to submit a PR. But would be nice to link to some documentation.

**Comment by kleinkk76** [comment]
https://github.com/Shopify/statsd-instrument/issues/321#issuecomment-1296873020 M
