### ISSUE TITLE
Use CaptureBackend in Test environment

### ISSUE THREAD

**Issue by nTraum** [Shopify/statsd-instrument#55]
Hi statsd-instrument team,

I want to provide convenient `RSpec` matchers for this gem (similar to your `minitest` assertions) and was wondering why the `CaptureBackend` is not used by default in test environments (but the `NullBackend` instead).

In my opinion this would simplify the implementation a lot, instead of mocking & replacing the `NullBackend` with a `CaptureBackend` in a block (as done currently), you'd just need to configure the Backend once (either in a `spec_helper` explicitly or via ENVs implicitly).

What do you think?

**Comment by wvanbergen** [comment]
Two reasons:

- First of all, we want to make sure the StatsD packet is actually generated inside the code block of the `assert` call. So we should only capture inside the block.
- Second: our test suite is big, and we generate lots of StatsD calls. This would require a lot of memory during the test run as we accumulate thousands of metrics.

In RSpec, I'd expect something like `expect { ... }.to generate_statsd_call(...)`. You can easily do the same trick with the block here.

**Comment by nTraum** [comment]
Valid points, thanks for the quick response!
