### ISSUE TITLE
Counting an object's property on success (metaprogramming)

### ISSUE THREAD

**Issue by ccoenen** [Shopify/statsd-instrument#56]
Is there a possibility to count an object's property on success?

Let's say i have a class like this

```ruby
class EasterBunny
  def eggs
    5
  end

  def hide
    rand > 0.5 # 50/50 chance of returning 'true'
  end
end
```

Now i would like to be able to instrument that class in a metaprogramming style

```ruby
EasterBunny.extend StatsD::Instrument
EasterBunny.statsd_count_if :hide, 'hidden'
```

This would increase the counter by 1 for every successful run.

But what i'd actually want to know would be "how many eggs were hidden", so in the example i'd need a way to increase the counter by `bunny.eggs` amount for every successful run.

Is there a metaprogramming way to do this? I saw the block-form of ..count_if, but that gets the return value of a function, not the object itself.

**Comment by wvanbergen** [comment]
There's no standard metaprogramming function for this. You either have to add the instrumentation to the method itself using raw `StatsD.increment` calls, or write your own metaprogramming method wrapper.

**Comment by ccoenen** [comment]
alright! thanks for the confirmation.
