### ISSUE TITLE
Get rid of the global object.

### ISSUE THREAD

**Issue by NikolayRys** [Shopify/statsd-instrument#64]
This is not a feature request, just a question if such feature would be useful. If it is, I also would like to implement it myself.
The point:
The gem is great, but it is implemented as global object(a module, to be precise), what leads to impossibility to use several different instances of it in one application, which can be very useful. I personally twice run in such circumstances where it was necessary and where our team had to switch to another competing gem. Once was necessary to have different prefixes and another time to have different servers where metrics are collected.
If the gem maintainer agrees that such functionality is welcome, I would implement it. Also, I guess, I can preserve the current interface doing it.

**Comment by wvanbergen** [comment]
Sure, as long as the singleton API continues to work as is, this is a good idea. Most logic already is in the `Backend` classes, but it would definitely be nice to move the remaining logic currently in the singleton to a class as well. :+1:

**Comment by wvanbergen** [comment]
We can close this now;  you can instantiate a `StatsD::Instrument::Client`, and use that to emit datagrams eithout using the singleton. The singleton object now uses a "default client" to send messages.

Die to its extensive use in production code, it's unlikely that we will ever remove the singleton object.
