### ISSUE TITLE
Instrumenting a Rails model fails

### ISSUE THREAD

**Issue by mustela** [Shopify/statsd-instrument#74]
It seems that extending a rails model "destroys" it completely. 

Suppose I have a rails model 

``` ruby
class User < ActiveRecord::Base
end

# See how many users I have
::User.all.count # => 20

# And I instrument it
::User.extend StatsD::Instrument

# If I try to run any operation on the model it is like it would lost the connection with the db or something really strange is happening 

::User.all.count  # => 0
```

And any other operation just fails, like creating new users, or anything related to the class. 

Does it make sense?

**Comment by wvanbergen** [comment]
This is probably due to both `ActiveRecord` and `StatsD::Instrument` using complex metaprogramming / monkeypatching to achieve their respective goals. It looks like these methods are interfering with each other in some way.

**Comment by dropofwill** [comment]
Just tried this on a bunch of our models, and everything seems fine...which makes me nervous.

Ruby 1.9 / Rails 4.1 / ActiveRecord 4.1:

```
Document.all.count # => 133
Document.extend StatsD::Instrument
Document.all.count # => 133
```
