### ISSUE TITLE
Histograms not working

### ISSUE THREAD

**Issue by davidpdrsn** [Shopify/statsd-instrument#79]
I have `StatsD` configured like so:

``` ruby
StatsD.backend = StatsD::Instrument::Backends::UDPBackend.new(
  "localhost:8125",
  :datadog,
)
```

But I'm seeing "Metric type :h not supported on statsd implementation" in the log.

I'm running on Heroku using [this buildpack](https://github.com/miketheman/heroku-buildpack-datadog) to install statsd itself.

Any ideas what I'm doing wrong?

**Comment by miketheman** [comment]
The error message appears to be from this line:
https://github.com/Shopify/statsd-instrument/blob/bdd9e4388804325713a9d274bf4860fbbc44bb20/lib/statsd/instrument/backends/udp_backend.rb#L16

However, a few lines later, it can be seen that histograms are a supported type. https://github.com/Shopify/statsd-instrument/blob/bdd9e4388804325713a9d274bf4860fbbc44bb20/lib/statsd/instrument/backends/udp_backend.rb#L28-L32

You haven't provided the method in which you are emitting this metric, only the setup mechanism for the backend - I tested a simple `StatsD.histogram('fooh', 42.4, tags: ["foo", "bar"])` and this works.

**Comment by davidpdrsn** [comment]
Here is the code that emits the metric

```ruby
ActiveSupport::Notifications.subscribe("process_action.rocket_pants") do |name, start, finish, id, payload|
  process_time = ((finish - start) * 1000).round

  controller = payload[:controller].underscore.sub("_controller", "").gsub("/", "_")
  action = payload[:action]

  StatsD.histogram(
    "request.processed.time_histogram.#{controller}.#{action}",
    process_time,
  )
end
```

**Comment by wvanbergen** [comment]
Closing this; this was an issue with the 2.x version, but should no longer cause issues on 3.x
