### ISSUE TITLE
New version breaks with RSpec version ~ 3.4

### ISSUE THREAD

**Issue by dkln** [Shopify/statsd-instrument#83]
O hi!

I get an error when I run my tests with version `2.0.12` with `rspec-core` version `3.4.1`:

```
lib/ruby/gems/2.3.0/gems/statsd-instrument-2.0.12/lib/statsd/instrument/matchers.rb:2:in `require': cannot load such file -- rspec/version (LoadError)
```

I looks this was introduced by commit 3dd6033c1e53810b5a3724f3b86a2b2849850f56. Version `2.0.11` seems to work fine.

**Comment by wvanbergen** [comment]
Weird; `lib/rspec/version.rb` is definitely still part of rspec: https://github.com/rspec/rspec/blob/master/lib/rspec/version.rb

**Comment by shaneog** [comment]
If you just use `rspec-rails` then the `rspec` meta-gem is not installed.
And then this version of the `statsd-instrument` gem breaks all tests with the message:

```
LoadError: cannot load such file -- rspec/version
```

Adding `gem 'rspec'` to the gemfile functions as a workaround.
