### ISSUE TITLE
Changelog out of date

### ISSUE THREAD

**Issue by knappe** [Shopify/statsd-instrument#85]
https://github.com/Shopify/statsd-instrument/blob/master/CHANGELOG.md shows 2.0.6, while 2.0.12 is latest on rubygems (https://rubygems.org/gems/statsd-instrument).

**Comment by sonalkr132** [comment]
I updated from 2.0.12 to 2.1.1

2.1.1

* Add `assert_statsd_calls` to from validating cases where one has
  multiple metrics with the same name and type being recorded, but
  with different options. #86

2.1.0

* Fix rspec-rails compatibility #84
* Add `value` keyword argument to all metric types. #87
