### ISSUE TITLE
support for events

### ISSUE THREAD

**Issue by jgoulah** [Shopify/statsd-instrument#89]
the [datadog version of statsd](https://github.com/DataDog/dogstatsd-ruby) has support for events, can we integrate similar functionality?  this will allow us to overlay vertical lines on the graphs to see when events happen

**Comment by wvanbergen** [comment]
Should be pretty easy to add.

Here's a go implementation of the packets we should be sending: https://github.com/Shopify/go-dogstatsd/blob/master/dogstatsd.go#L139-L153
