### ISSUE TITLE
Improve Error Messages

### ISSUE THREAD

**Issue by itsWill** [Shopify/statsd-instrument#98]
Here's a sample error I received while working with this gem. 

``` 
ArgumentError: A value is required for metric type :h.
```

I think we could improve the message here to something like

```
ArgumentError:  histogram was called with the value parameter set to nil
```

The error wasn't hard to debug but it could have been easier, I don't mind taking ownership of this one

@wvanbergen

**Comment by wvanbergen** [comment]
Closing this; this gem has been extensively refactored to not use hashes as arguments anymore, but use regular arguments are keyword arguments instead. Error messages for wrong argument usage are now the standard Ruby error messages.
